# Generated by Django 5.2.6 on 2025-09-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dribbble',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
